name: Flutter CD

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'dev'
    - name: Install dependencies
      run: flutter pub get
    - name: Build APK
      run: |
        flutter build apk --release --split-per-abi
    - name: Create changelog
      run: |
        TAG_COUNT=$(git tag | wc -l)
        CURRENT_TAG=$(git tag --sort=-committerdate | head -1)
        if [[ $TAG_COUNT -gt 2 ]]; then
          PREVIOUS_TAG=$(git tag --sort=-committerdate | sed -n 2p)
          git log --pretty=format:%s ${CURRENT_TAG}..${PREVIOUS_TAG} > CHANGELOG.md
        else
          git log --pretty=format:%s ${CURRENT_TAG} > CHANGELOG.md
        fi
    - name: Extract tag name
      id: tag
      uses: actions/github-script@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        result-encoding: string
        script: |
          return context.payload.ref.replace(/refs.tags./, '');
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body_path: ./CHANGELOG.md
    - name: Upload release APK
      id: upload-release-apk
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
        asset_name: todo-app-armeabi-v7a-${{ steps.tag.outputs.result }}.apk
        asset_content_type: application/vnd.android.package-archive
